image: maven:latest

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml -Pdspace-lni"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dmirage2.on=true -Djavax.net.ssl.trustStorePassword=changeit -Djava.net.preferIPv4Stack=true"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - curl -v -u $MAVEN_REPO_USER:$MAVEN_REPO_PASS https://repo.its.lib.vt.edu/repository/vtechworks/org/dspace/dspace-parent/5.9-SNAPSHOT/dspace-parent-5.9-20181009.135733-1.pom --request PUT --data @pom.xml

